---
title: "Principios y Prácticas de SEM y MLM (5a ed.)"
subtitle: "Tema 0. Presentación del curso"
author: "Efraín García Sánchez"
date: "08/05/2026"
toc: true
toc-title: "Contenidos"
format:
  html:
    toc: true
    toc-depth: 2
    embed-resources: true
execute:
  echo: true
  eval: true
  warning: false
  message: false
editor: source
---

# Preparar el ambiente de trabajo

## Descargar los materiales del curso

## Instalar paquetes 

```{r}
#| eval: false
# Instalar todos los paquetes necesarios para las prácticas del curso.
paquetes <- c(
  "car",
  "correlation",
  "dplyr",
  "easystats",
  "emmeans",
  "GGally",
  "haven",
  "here",
  "marginaleffects",
  "modelbased",
  "parameters",
  "performance",
  "psych",
  "readr",
  "sjmisc",
  "sjPlot",
  "tidyverse"
)

install.packages(paquetes)
```

## Cargar paquetes

```{r}
library(car)
library(correlation)
library(dplyr)
library(easystats)
library(emmeans)
library(GGally)
library(haven)
library(here)
library(marginaleffects)
library(modelbased)
library(parameters)
library(performance)
library(psych)
library(readr)
library(sjmisc)
library(sjPlot)
library(tidyverse)
```
